name: Infection

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  Infection:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          coverage: "pcov"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: Run Infection
        run: vendor/bin/roave-infection-static-analysis-plugin --threads=$(nproc)
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

