name: Infection

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 17 * * *"

jobs:
  Infection:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@2.6.0
        with:
          php-version: 7.4
          coverage: xdebug
          extensions: json

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Infection
        run: vendor/bin/infection --min-msi=64 --min-covered-msi=65 --log-verbosity=none -s
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
